version: "3.8"

services:
  postgres:
    image: postgres:15 # Use the latest stable version of Postgres
    container_name: postgres_local
    restart: always
    ports:
      - "5432:5432" # Map local port 5432 to container port 5432
    environment:
      POSTGRES_USER: dev # Set your database username
      POSTGRES_PASSWORD: dev # Set your database password
      POSTGRES_DB: dev # Set your default database
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist Postgres data locally

volumes:
  postgres_data:
